package me.eva.buidmgui.gui.wizard;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class WizardFirst extends JPanel {
    private JPanel root;
    private EntityCreationContext context;


    public WizardFirst(LayoutManager layout, EntityCreationContext context) {
        super(layout);
        this.context = context;
        $$$setupUI$$$();
        add(root);
    }



    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JTextPane textPane1 = new JTextPane();
        textPane1.setText("Wilkommen im EntityCreationWizard.\n\nIn den folgenden Schritten wird ein Mandant (Entity) mitsamt Standort(en), Parametern und Organisationsstruktur angelegt.\n\nUngespeicherte Änderungen gehen beim Abbruch (über den Button \"abbrechen\" oder Drücken der \"ESC\"-Taste) verloren.");
        root.add(textPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}