package me.eva.buidmgui.gui.wizard;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class WizardFinal extends JPanel {
    private JTextPane sqlPane;
    private JPanel panel1;

    public WizardFinal(LayoutManager layout, EntityCreationWizard wizard) {
        super(layout);
        add(panel1);
    }

    public String[] generateSql(EntityCreationContext context) {
        String insertEntityConfigSql = String.format("INSERT INTO ENTITYCONFIGURATION (ENTITYNAME, PARAMETER_NAME, PARAMETER_VALUE, ACTIVE) VALUES (\"%s\", \"%s\", \"%s\", \"%s\")",
                context.getEntityId(), "ENTITYNAME", context.getEntityName(), 1);

        String insertEntityLocationSql = String.format("INSERT INTO ENTITYLOCATION (ENTITY_NAME, LOCATION_ID, LOCATION_NAME, LOCATION_STREET, LOCATION_POSTCODE, LOCATION_CITY, LOCATION_COUNTRY, INTERNAL_LOCATION_PREFIX, EXTERNAL_LOCATION_PREFIX, FAX_LOCATION_PREFIX, ACTIVE) VALUES (\"%s\",\"%s\",\"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\")"
                , context.getEntityName(), context.getEntityId(), context.getEntityName(), context.getLocationStreet(), context.getLocationPostcode(), context.getLocationCity(), context.getLocationCountry(), context.getTelInternal(), context.getTelExternal(), context.getFax(), 1);

        sqlPane.setText(insertEntityConfigSql + "\n" + insertEntityLocationSql);

        return new String[]{insertEntityConfigSql, insertEntityLocationSql};
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        sqlPane = new JTextPane();
        panel1.add(sqlPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}