package me.eva.buidmgui.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import me.eva.buidmgui.util.Utilities;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Scanner;
import java.util.stream.Collectors;

public class ConverterPage extends JDialog {
    private JPanel root;
    private JButton browseButton;
    private JTextPane textPane;
    private JLabel currentFileLabel;


    public ConverterPage(Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Nach SQL konvertieren");

        textPane.setFont(new Font("Consolas", Font.PLAIN, 18));

        browseButton.addActionListener(e -> {
            JFileChooser fileChooser = new JFileChooser("C:/User".replace("/", File.separator), FileSystemView.getFileSystemView());
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fileChooser.setAcceptAllFileFilterUsed(false);
            fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("CSV Dateien", "csv"));
            fileChooser.showOpenDialog(parent);

            File file = fileChooser.getSelectedFile();
            if (file == null) {
                throw new IllegalArgumentException("File must not be null!");
            }

            currentFileLabel.setText(file.getName());
            long totalLength = file.length();
            long readLength = 0;

            try {
                Scanner scanner = new Scanner(file);
                String firstLine = scanner.nextLine();
                ArrayList<String> lines = new ArrayList<>();

                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    lines.add(line);
                }
                scanner.close();

                lines.stream()
                        .map(str -> str.split(";"))
                        .sorted(Comparator.comparing(o -> o[0]))
                        .map(strings -> {
                            return String.format("INSERT INTO ENTITYCONFIGURATION (ENTITYNAME, PARAMETER_NAME, PARAMETER_VALUE, `ACTIVE`) VALUES ('%s','%s','%s','%s');", strings[0], strings[1], strings[2], strings[3]);
                        })
                        .forEach(line -> {
                            textPane.setText(textPane.getText() + line + System.lineSeparator());
                        });


            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(parent, "Es gab einen Fehler beim Lesen der Datei.", "Konvertierungsfehler", JOptionPane.ERROR_MESSAGE);
            }
        });


        setSize(600, 400);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setContentPane(root);
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        root.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        browseButton = new JButton();
        browseButton.setText("Durchsuchen...");
        root.add(browseButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        currentFileLabel = new JLabel();
        currentFileLabel.setText("keine Datei ausgewählt");
        root.add(currentFileLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(329, 16), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        root.add(scrollPane1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        textPane = new JTextPane();
        textPane.setEditable(false);
        scrollPane1.setViewportView(textPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
