package me.eva.buidmgui.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import me.eva.buidmgui.Main;
import me.eva.buidmgui.net.DatabaseConnection;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.sql.SQLException;

public class LoginPage extends JFrame {
    private JPanel root;
    private JTextField userTextField;
    private JComboBox<String> hostsComboBox;
    private JPasswordField passwordField;
    private JLabel passwordLabel;
    private JLabel hostLabel;
    private JLabel userLabel;
    private JButton connectButton;
    private JButton cancelButton;

    public LoginPage() {
        $$$setupUI$$$();
        setTitle("Anmelden");
        setContentPane(root);
        setResizable(false);

        cancelButton.addActionListener(e -> dispose());
        connectButton.addActionListener(e -> {
            try {
                DatabaseConnection connection = new DatabaseConnection(
                        DatabaseConnection.resolveHost((String) hostsComboBox.getSelectedItem()),
                        "identityiqPlugin",
                        userTextField.getText(),
                        passwordField.getText()
                );
                MainPage mainPage = new MainPage(connection);
                dispose();

            } catch (SQLException | NullPointerException ex) {
                JOptionPane.showMessageDialog(root, ex.getMessage(), "Verbindungsfehler", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
                System.exit(1);
            }
        });

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        pack();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        hostsComboBox = new JComboBox<>();
        hostsComboBox.addItem("192.168.178.91");
        hostsComboBox.addItem("DEV");
        hostsComboBox.addItem("REF");
        hostsComboBox.addItem("PROD");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        root.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        userTextField = new JTextField();
        root.add(userTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        hostsComboBox.setEditable(true);
        root.add(hostsComboBox, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordField = new JPasswordField();
        root.add(passwordField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        userLabel = new JLabel();
        userLabel.setText("Benutzer");
        root.add(userLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordLabel = new JLabel();
        passwordLabel.setText("Passwort");
        root.add(passwordLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        hostLabel = new JLabel();
        hostLabel.setText("Umgebung/Host");
        root.add(hostLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        root.add(panel1, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        connectButton = new JButton();
        connectButton.setHorizontalAlignment(4);
        connectButton.setSelected(false);
        connectButton.setText("Verbinden");
        panel1.add(connectButton);
        cancelButton = new JButton();
        cancelButton.setHorizontalAlignment(4);
        cancelButton.setText("Abbrechen");
        panel1.add(cancelButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}